config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/home', to: 'pages#home'


  # get '/recipes', to: 'recipes#index'
  # get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  # post '/recipes', to: 'recipes#create'
  # get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  # patch '/recipes/:id', to: 'recipes#update'
  # get '/recipes/:id', to: 'recipes#show', as: 'recipe'
  # delete '/recipes/:id', to: 'recipes#destroy'

  resources :recipes do
    member do
      post 'like'
      resources :comments
    end
  end

  resources :chefs, except: [:new, :destroy]

  get '/register', to: 'chefs#new'

  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'

  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]


end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  validate :picture_size
  belongs_to :chef
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :recipe_styles, dependent: :destroy
  has_many :styles, through: :recipe_styles
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  validates :chef_id, presence: true
  validates :name, presence: true, length: { minimum: 5, maximum: 100 }
  validates :summary, presence: true, length: {minimum: 10, maximum: 150}
  validates :description, presence: true, length: {minimum: 20, maximum: 500 }

  default_scope -> {order(updated_at: :desc)}

  def thumbs_up_total
    self.likes.where(like: true).size
  end

  def thumbs_down_total
    self.likes.where(like: false).size
  end

  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "Should be less than 5MB")
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :like]
  before_action :require_user, except: [:show, :index, :like]
  before_action :require_user_like, only: [:like]
  before_action :require_same_user, only: [:edit,:update]
  before_action :admin_user, only: [:destroy]


  def index
    # @recipes = Recipe.all.sort_by{|likes| likes.thumbs_up_total}.reverse
    @recipes = Recipe.paginate(page: params[:page], per_page: 5)
  end

  def show
    # @comments = @recipe.comments
    # @recipe = Recipe.find(params[:id]) used to set_recipe
    # binding.pry
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    # @recipe.chef = Chef.find(5) #temporary implementation
    @recipe.chef = current_user
    if @recipe.save
      flash[:success] = "Recipe was created Successfully"
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @recipe.update(recipe_params)
      ##
      flash[:success] = "Recipe Updated Successfully!"
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  def like
    like = Like.create(like: params[:like], chef: current_user, recipe: @recipe)
    if like.valid?
      flash[:success] = "Voting done"
      redirect_to :back
    else
      flash[:danger] = "You can like/dislike a recipe once"
      redirect_to :back
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id]).destroy
    flash[:success] = "Recipe Deleted"
    redirect_to recipes_path
  end

  private

    def recipe_params
      params.require(:recipe).permit(:name, :summary, :description, :picture, style_ids: [] , ingredient_ids: [])
    end

    def require_same_user
      if current_user != @recipe.chef and !current_user.admin
        flash[:danger] = "You don't have the permission to edit"
        redirect_to recipes_path
      end
    end

    def require_user_like
      if !logged_in?
        flash[:danger] = "You must be logged in"
        redirect_to :back
      end
    end

    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def admin_user
      redirect_to recipes_path unless current_user.admin?
    end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>
<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for @recipe, html: { multipart: true } do |f| %>
      <%= f.label :Name %>
      <%= f.text_field :name %><br/>

      <%= f.label :Summary %>
      <%= f.text_field :summary %><br/>

      <%= f.label :Description %>
      <%= f.text_area :description, rows: 10 %><br/>

      <strong>Styles:</strong>
      <%= f.collection_check_boxes :style_ids, Style.all, :id, :name do |cb| %>
      <%= cb.label(class: "checkbox-inline") {cb.check_box(class: "checkbox") + cb.text } %>
      <% end %>
      <br><br>

      <strong>Ingedients:</strong>
      <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |ingredient| %>
      <%= ingredient.label(class: "checkbox-inline") {ingredient.check_box(class: "checkbox") + ingredient.text } %>
      <% end %>
      <br>
      <br>

      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
      </span>

      <%= f.submit(@recipe.new_record? ? 'Create Recipe' : 'Update Recipe', class: "btn btn-success")  %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#recipe_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB, Please choose a smaller file');
    }
  });
</script>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit Recipe" %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "All Recipes" %>

<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to "Recipes", recipes_path %>
  </li>
  <li>
    <%= link_to "Chefs", chefs_path %>
  </li>
</ul>

<%= will_paginate %>
<% @recipes.each do |recipe| %>
  <div class="row">

    <div class="col-md-2">
      <section class="chef_info center">
        <%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef) %>
        <h5>Chef name: <%= recipe.chef.chefname %></h5>
      </section>
    </div>

    <div class="col-lg-6 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= recipe.summary %></p>

      <% if recipe.styles.any? %>
        <p>Recipe Style: <%= render recipe.styles %></p>
      <% end %>

      <% if recipe.ingredients.any? %>
        <p>Recipe Ingredients: <%= render recipe.ingredients %></p>
      <% end %>
      <p>
        <span class="quiet"><small>Created: <%= time_ago_in_words(recipe.created_at) %> ago,</small></span>
        <span class="quiet"><small>Updated <%= time_ago_in_words(recipe.updated_at)%> ago</small></span>
      </p>

      <div class="pull-right">
        <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i>
          &nbsp
          <%=  recipe.thumbs_up_total %>
        <% end %>
        &nbsp&nbsp
        <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp
          <%= recipe.thumbs_down_total %>
        <% end %>

        &nbsp&nbsp
        <% if recipe.comments.any? %>
        <%= link_to "Comments", recipe_path(recipe) %> &nbsp
        <%= link_to recipe.comments.size, recipe_path(recipe) %>
        <%#= recipe.comments.size %> &nbsp
        <% else %>
        <%= link_to "Post Comment", new_comment_path(recipe) %>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
        <%= image_tag(recipe.picture.url, size: "250x150", class: "gravatar_for") if recipe.picture? %>
    </div>
  </div>
  <hr/>

<% end %>
<%= will_paginate %>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "Create a new Recipe" %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class="row">
  <div class="col-md-4 pull-right center">
    <%= link_to gravatar_for(@recipe.chef, size: 200), chef_path(@recipe.chef) %>
    <p>
       <h5>Brought to you by: <%= @recipe.chef.chefname %></h5>
    </p>
  </div>
  <div class="col-md-8">
    <% if logged_in? && (@recipe.chef == current_user || current_user.admin?) %>
      <%= link_to "Edit this Recipe", edit_recipe_path(@recipe), class: "btn btn-success pull-right" %>
    <% end %>
    <% if logged_in? && current_user.admin? %>
      <%= link_to "[Delete Recipe]", @recipe, method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
    <h3><%= @recipe.summary %></h3>
    <div class="show_recipe">
        <%= image_tag(@recipe.picture.url, class:"gravatar_for") if @recipe.picture? %>
    </div>
    <div class="well">
      <% if @recipe.styles.any? %>
        <p>Recipe Style: <%= render @recipe.styles %></p>
      <% end %>

      <% if @recipe.ingredients.any? %>
        <p>Recipe Ingredients: <%= render @recipe.ingredients %></p>
      <% end %>
      <p>
        <strong>Steps:</strong>
      </p>
      <%= simple_format(@recipe.description) %>
      <div class="pull-right">
        <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i>
          &nbsp
          <%=  @recipe.thumbs_up_total %>
        <% end %>
        &nbsp&nbsp
        <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp
          <%= @recipe.thumbs_down_total %>
        <% end %>

        &nbsp &nbsp
        <%= link_to "Post Comment", new_comment_path(@recipe) %>
      </div>
  </div>
  <div class="well">
    <p>
      <% if @recipe.comments.any? %>
        <p>
         <h1>Listing Comments</h1>
         <hr/>
       </p>
       <p><% @recipe.comments.each do |comment| %></p>
       <p>
         <%= comment.comment %>
         <p>
           <span class="quiet"><small> By <%= link_to comment.chef.chefname, chefs_path %></small></span>
         </p>
         <hr/>
         <% end %>
         <% end %>
       </p>
    </p>
  </div>
  </div>
</div>

<h5><%= link_to "Return to Recipes", recipes_path, class: "btn btn-warning btn-small" %></h5>