config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/home', to: 'pages#home'


  # get '/recipes', to: 'recipes#index'
  # get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  # post '/recipes', to: 'recipes#create'
  # get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  # patch '/recipes/:id', to: 'recipes#update'
  # get '/recipes/:id', to: 'recipes#show', as: 'recipe'
  # delete '/recipes/:id', to: 'recipes#destroy'

  resources :recipes do
    member do
      post 'like'
      resources :comments
    end
  end

  resources :chefs, except: [:new, :destroy]

  get '/register', to: 'chefs#new'

  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'

  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]


end

app/views/pages/home.html.erb
<div class="center jumbotron">
	<h1>Welcome to My Recipes App</h1>

	<h2>This is the home Page</h2>

	<%= link_to "Sign Up", register_path, class: "btn btn-large btn-success" %>
</div>

<div class="row">
	<div class="col-lg-4">
		<h3 class="midrow">
			View recipes as Guest User
		</h3>
		<h2 class="left">Browse and View Recipies as Guest and Signup later</h2>
		<p><%= link_to "Browse Recipies", recipes_path, class: "btn btn-warning btn-small" %></p>
	</div>

	<div class="col-lg-4">
		<h3 class="midrow">
			Sign in to your account
		</h3>
		<h2 class="left">Add/Update your recipes, create reviews, rate and like</h2>
		<p><%= link_to "Login to your account",login_path, class: "btn btn-warning btn-small" %></p>
	</div>

	<div class="col-lg-4">
		<h3 class="midrow">
			View recipes as Guest User
		</h3>
		<h2 class="left">Browse and View Recipies as Guest and Signup later</h2>
		<p><%= link_to "Browse Recipies", "", class: "btn btn-warning btn-small" %></p>
	</div>
</div>