config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/home', to: 'pages#home'


  # get '/recipes', to: 'recipes#index'
  # get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  # post '/recipes', to: 'recipes#create'
  # get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  # patch '/recipes/:id', to: 'recipes#update'
  # get '/recipes/:id', to: 'recipes#show', as: 'recipe'
  # delete '/recipes/:id', to: 'recipes#destroy'

  resources :recipes do
    member do
      post 'like'
      resources :comments
    end
  end

  resources :chefs, except: [:new, :destroy]

  get '/register', to: 'chefs#new'

  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'

  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]


end

app/views/layouts/_footer.html.erb
<div class="footer">
	<p>&copy; MyRecipies</p>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
		<div class="container">
			<%= link_to "myRecipe",root_path, class: "btn btn-lg btn-success", id: "logo" %>
			<ul class="nav_ul_item">
				<li class="dropdown">
					<%= link_to '#', class:"btn bt-default btn-danger  dropdown-toggle", "data-toggle" => "dropdown" do %>
						Styles <b class="caret"></b>
					<% end %>
					<ul class="dropdown-menu">
						<% Style.all.each do |style| %>
						<li><%= link_to style.name, style_path(style) %></li>
						<% end %>
						<% if logged_in? %>
							<li class="divider"></li>
							<li>
								<%= link_to(new_style_path) do %>
									New Style
								<% end %>
							</li>
						<% end %>
					</ul>
				</li>
			</ul>

			<ul class="nav_ul_item">
				<li class="dropdown">
					<%= link_to '#', class:"btn bt-default btn-danger  dropdown-toggle", "data-toggle" => "dropdown" do %>
						Ingredients <b class="caret"></b>
					<% end %>
					<ul class="dropdown-menu">
						<% Ingredient.all.each do |ingredient| %>
						<li><%= link_to ingredient.name, ingredient_path(ingredient) %></li>
						<% end %>
						<% if logged_in? %>
							<li class="divider"></li>
							<li>
								<%= link_to(new_ingredient_path) do %>
									New Ingredient
								<% end %>
							</li>
						<% end %>
					</ul>
				</li>
			</ul>

			<% if logged_in? %>
					<div class="nav_item">
						<%= link_to "New Recipe",new_recipe_path , class: "btn btn-default btn-warning" %>
					</div>
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<%= link_to '#', class:"btn bt-default nav_item dropdown-toggle", "data-toggle" => "dropdown" do %>
								<%= current_user.chefname %> <b class="caret"></b>
							<% end %>
							<ul class="dropdown-menu">
								<li><%= link_to "View Profile", chef_path(current_user) %></li>
								<li><%= link_to "Edit Profile", edit_chef_path(current_user) %></li>
								<li><%= link_to "Logout", logout_path %></li>
							</ul>
						</li>
					</ul>
			<% else %>
				<div class="nav navbar-nav navbar-right">
					<%= link_to "Login",login_path, class: "btn btn-default btn-success nav_item" %>
				</div>
			<% end %>

		</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myrecipe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navigation' %>
	<div class="container">
    <%= render 'layouts/messages' %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>